export let pantryItems = [
  {
    id: 1,
    name: 'Tomatoes',
    imageFP: require('../../assets/temp-images/tomatoe-r.png'),
    typeText: 'Dry pantry',
    type: 3,
    count: 4,
  },
  {
    id: 2,
    name: 'Mozzarella cheese',
    imageFP: require('../../assets/temp-images/mozzarella-r.png'),
    typeText: 'Fridge',
    type: 1,
    count: 5,
  },
  {
    id: 3,
    name: 'T-bone steak',
    imageFP: require('../../assets/temp-images/steak-r.png'),
    typeText: 'Freezer',
    type: 2,
    count: 3,
  },
  {
    id: 4,
    name: 'Penne pasta bag',
    imageFP: require('../../assets/temp-images/penne-r.png'),
    typeText: 'Dry pantry',
    type: 3,
    count: 1,
  },
  {
    id: 5,
    name: 'Granola bites',
    imageFP: require('../../assets/temp-images/granola-r.png'),
    typeText: 'Dry pantry',
    type: 3,
    count: 2,
  },
  {
    id: 6,
    name: 'Brocolli',
    imageFP: require('../../assets/temp-images/broccolli-r.png'),
    typeText: 'Fridge',
    type: 1,
    count: 2,
  },
  {
    id: 7,
    name: 'human meat',
    imageFP: require('../../assets/temp-images/mystery-r.png'),
    typeText: 'Freezer',
    type: 2,
    count: 10,
  },
];
